autopkg/wycomco-recipes

bimcollab_zoom/BIMcollabZOOM.download.recipe
bimcollab_zoom/BIMcollabZOOM.pkg.recipe

Neither of these recipes have a MunkiImporter process, so the Munki-related input variables serve no purpose and may cause confusion for admins who override the recipes.

Remove Munki-related input variables from download/pkg recipes

---

bimcollab_zoom/BIMcollabZOOM.download.recipe
bimcollab_zoom/BIMcollabZOOM.munki.recipe
bimcollab_zoom/BIMcollabZOOM.pkg.recipe
sipgate_softphone/sipgate-softphone.download.recipe

A typo was [found and fixed](https://github.com/autopkg/autopkg/commit/983087f63d49c8dbc4dbbd6bb5ced34321c59ac6) in the template AutoPkg uses when the `autopkg new-recipe` command is used. This PR makes the same change in your recipes that are affected by the typo.

Fix MinimumVersion key

---

Pragli/Pragli.download.recipe
Pragli/Pragli.munki.recipe

Pragli is now called "Pragli (Pesto)" and will probably once again be changed to Pesto. Since the download URL is created dynamically by JavaScript code, URLTextSearcher does not work without a custom processor. The URL is again hard-coded into the download recipe.

Pragli renamed to Pesto

---

SharedProcessors/MunkiAutoStaging.py
archicad_updates/ARCHICADUpdatesProcessor.py

As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …

Update Python path in processors to reflect changes in macOS 12.3+

---

Foxit/FoxitPDFReader.download.recipe
Foxit/FoxitPDFReader.munki.recipe

Download and Munki recipes for [Foxit PDF Reader](https://www.foxit.com/pdf-reader/). The download url seems to be static and redirects to the actual pkg download.
Used our common approaches to specify the minimum_os_version and a proper installs array.
Since the version of the downloaded package does not match the version of the installed app, I am overriding the version, as well.

Foxit Reader

---

archicad_updates/ARCHICADUpdate.download.recipe
archicad_updates/ARCHICADUpdate.munki.recipe
archicad_updates/ARCHICADUpdatesProcessor.py

Support ARM builds by adding an ARCHITECTURE option, which falls back to INTEL. This became urgent, since Graphisoft published an ARM only build with a higher build number than the corresponding Intel build.

ARCHICAD: Support for ARM builds

---

archicad_updates/ARCHICADUpdate.download.recipe
archicad_updates/ARCHICADUpdate.munki.recipe

Only descriptions updated. Can also be done when v27 comes out to avoid unneeded parent's trust updates (no change to keys or processors).

archicad_updates: updated infos to major versions

---

archicad_updates/ARCHICADUpdate.munki.recipe

To better distinguish between different architectures I have added the architecture to display_name and name attributes.

AC: Add architecture to name and display name

---

archicad_updates/ARCHICADUpdatesProcessor.py

The previously used update feed didn't include the most recent updates anymore. With this release we are parsing the public available website for the needed data.

Fix for Archicad download processor

---

bimcollab_zoom/BIMcollabZOOM.pkg.recipe

...since included frameworks did not match anymore. It now just checks for the correct developer certificate.

BIMcollab: Removed identifier from expected code signature

---

Bitwarden/Bitwarden.munki.recipe

[drewdriver-recipes](https://github.com/autopkg/drewdiver-recipes/tree/master/Bitwarden) only takes care of Jamf workflows.
Tested succesfully:
- Download of app in repo
- minimum_os_version is evaluated

Bitwarden: Initial commit

---

archicad_updates/ARCHICADUpdate.munki.recipe

By now we have added the supported_architecture key as part of the additional_pkgsinfo var. But this lead to forcibly limiting the resulting Munki item to this architecture. Moving the key to the input var leaves the Munki admin to choose whether he or she wants to limit the package to an architecture.

Archicad: Move supported_architecture to pkginfo in input var

---

LibreOffice/LibreOfficeLangPack.download.recipe
LibreOffice/LibreOfficeLangPack.munki.recipe
LibreOffice/LibreOfficeLangPack.pkg.recipe

LibreOffice has changed its naming of 'fresh' and 'still' to 'Latest' and 'Previous'. The changes from @hjuutilainen's recipes have been taken over accordingly.
Instructions on how to obtain the proper language code have been added.

Libreoffice releases

---

SharedProcessors/JamfMultiUploader.py

You may now add a "disabled" key to either the `jamf_uploader_processor_parameters` or to a `jamf_server_configs` to skip the process for the given JSS.
Example for a `jamf_uploader_processor_parameters` in a recipe:
```XML
<dict>
<key>Arguments</key>
<dict>
<key>jamf_uploader_name</key>
<string>com.github.grahampugh.jamf-upload.processors/JamfPatchUploader</string>
<key>jamf_uploader_processor_parameters</key>
<dict>
<key>default</key>
<dict>
<key>patch_softwaretitle</key>
<string>%SOFTWARE_TITLE%</string>
<key>patch_template</key>
<string>jamf_patch_template_selfservice_de.xml</string>
<key>replace_patch</key>
<false/>
</dict>
<key>https://myveryspecialjss.jamfcloud.com</key>
<dict>
<key>disabled</key>
<true/>
</dict>
</dict>
</dict>
<key>Processor</key> …
```

Jamf Multi Uploader: Allow disabling of JSS configs

---

PDFExpert/PDF_Expert.munki.recipe

Tested successfully with different name (PDF_Expert instead of PDF Expert). minimum_os_version is set in munki plist, unneeded leftovers in cache directory is deleted.

PDF Expert: Initial commit

---

.pre-commit-config.yaml

Updated accordingly to [homebysix](https://github.com/autopkg/homebysix-recipes/blob/master/.pre-commit-config.yaml). `pre-commit run --all-files` ran fine, showing only known errors. Tested against AutoPkg 2.7.3.

pre-commit-config: Updated revisions

---

CitrixWorkspace/CitrixWorkspaceUniversal.munki.recipe

Parent recipes from @rtrouton are no longer available. Also, another munki recipe already exists at [hjuutilainen-recipes](https://github.com/autopkg/hjuutilainen-recipes/blob/master/CitrixReceiver/CitrixWorkspace.munki.recipe) that is fulfilling the same task. Please switch to that parent recipe. This recipe will be removed in the future.

Citrix Workspace: added DeprecationWarning

---

ClipStudioPaint/ClipStudioPaint.download.recipe
ClipStudioPaint/ClipStudioPaint.munki.recipe
ClipStudioPaint/ClipStudioPaint.pkg.recipe

The download URL is outdated. Since none of our customers uses this recipe and no other AutoPkg user has complained since at least v2.0.0, we are deprecating these recipes.

Added DeprecationWarning and StopProcessingIf to all recipes

---

airprint-ppd/airprint-ppd.download.recipe

This PR adds the missing code signature verification requirement for AirPrint PPD.
Here's the CodeSignatureVerifier section of the verbose recipe run output:
```
CodeSignatureVerifier
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "airprint_ppd.pkg":
CodeSignatureVerifier:    Status: signed by a developer certificate issued by Apple for distribution
CodeSignatureVerifier:    Notarization: trusted by the Apple notary service
CodeSignatureVerifier:    Signed with a trusted timestamp on: 2022-02-25 14:13:49 +0000
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: wycomco GmbH (CD4727XSC2)
CodeSignatureVerifier:        SHA256 Fingerprint:
CodeSignatureVerifier:            ED A9 0E 1D 70 63 B5 7A A0 …
```

Fix code signature verification in AirPrint PPD recipe

---

archicad_updates/ARCHICADUpdate.download.recipe
archicad_updates/ARCHICADUpdate.munki.recipe
archicad_updates/ARCHICADUpdatesProcessor.py

`supported_architecture` was not specified in the munki.recipe, this was fixed by adding a new variable.
When doing a manual `curl` on `https://graphisoft.com/de/service-support/downloads`, no current updates can be found for at least the INT and GER versions. The updates are shown on the website when navigating to "Updates" and the respective language and version, though.
Output of `autopkg run -vvq ARCHICADUpdate.download.recipe`:
```
Processing ARCHICADUpdate.download.recipe...
WARNING: ARCHICADUpdate.download.recipe is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
ARCHICADUpdatesProcessor
{'Input': {'ARCHITECTURE': 'INTEL',
'localization': 'INT',
'major_version': '26',
'release_type': 'FULL'}}
Unable to find a url based on the parameters provided. …
```

Fix ac download

---

archicad_updates/ARCHICADUpdate.munki.recipe

The output variable `%supported_architecture%` of the ARCHICADUpdatesProcessor was not evaluated in the `pkginfo` dict. Moving the key and array into the `MunkiPkginfoMerger` processor leads to the variable being set correctly in the resulting plists.
This eliminates the need to hard-code the appropriate architecture (arm64 or x86_64) into an override.

Archicad: move %supported_architecture% key into processor

---

.pre-commit-config.yaml
SharedProcessors/JamfMultiUploader.py
SharedProcessors/MunkiAutoStaging.py
SharedProcessors/MunkiRepoTeamsNotifier.py
archicad_updates/ARCHICADUpdatesProcessor.py

`pyupgrade` was added to the pre-commit repos. It is added to ensure compatibility with version 3.8 at the moment, as done by homebysix.
Several fixes have been done to processors:
- remove unneeded encoding, absolute_import lines and IOError (defaults or removed in python3)
- formatting issues
One thing to consider: In `MunkiAutoStaging.py`, the module `distutils.version` is used. This is deprecated in Python 3.10 (current version of `/usr/local/autopkg/python` and will be removed in Python 3.12. Replacement of this module has not been done, since the pull requester is not as good in python as the reviewer is.

Updated pre-commit config, fixed proposals to processors
